Test argo update check sed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -72,6 +72,15 @@ jobs:
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
+
+      - name: Check for sed
+        run: |
+          if ! command -v sed &> /dev/null
+          then
+            echo "sed could not be found"
+            exit 1
+          fi
+
       - name: Update values.yaml
         run: |
           echo "Before sed:"
@@ -79,8 +88,8 @@ jobs:
           sed -i "s/^  tag:.*/  tag: ${{ steps.vars.outputs.short_sha }}/" module_4/homework-step-final/helm_charts/python-app/values.yaml
           echo "After sed:"
           cat module_4/homework-step-final/helm_charts/python-app/values.yaml
+
       - name: Commit and Push changes
-        if: ${{ github.event_name == 'push' }}
         env:
           GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
         run: |
@@ -92,5 +101,3 @@ jobs:
           else
             git commit -m "Update Docker image tag to ${{ steps.vars.outputs.short_sha }}"
             git push origin main
-          fi
-
