corrected test_application 2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,8 +10,7 @@ on:
       - 'module_4/homework-step-final/**' # comment out for debugging
 
 # only for debugging
-#     - '**'
-jobs:
+      - '**'
 #  list_files:
 #    runs-on: ubuntu-latest
 #    steps:
@@ -22,47 +21,45 @@ jobs:
 #
 #    - name: List files in the Dockerfile directory
 #      run: ls -la module_4/homework-step-final/
-
+jobs:
   build:
     needs: list_files
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
-
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-
-    - name: Build and push
-      uses: docker/build-push-action@v3
-      with:
-        context: ./module_4/homework-step-final
-        file: ./module_4/homework-step-final/Dockerfile
-        push: true
-        tags: yourhostel/devops-final:latest
+      - uses: actions/checkout@v3
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build and push
+        uses: docker/build-push-action@v3
+        with:
+          context: ./module_4/homework-step-final
+          file: ./module_4/homework-step-final/Dockerfile
+          push: true
+          tags: yourhostel/devops-final:latest
 
   test_application:
     needs: build
     runs-on: ubuntu-latest
     steps:
-    - name: Pull and run Docker image
-      run: |
-        docker pull yourhostel/devops-final:latest
-        docker run -d -p 8080:8080 --name myapp yourhostel/devops-final:latest
-    - name: Check application response
-      run: |
-        sleep 10
-        response=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)
-        if [ "$response" -eq 200 ]; then
-          echo "Application responded with 200 OK"
-        else
-          echo "Application failed to respond with 200 OK"
-          exit 1
-        fi
+      - name: Pull and run Docker image
+        run: |
+          docker pull yourhostel/devops-final:latest
+          docker run -d -p 8080:8080 --name myapp yourhostel/devops-final:latest
+      - name: Check application response
+        run: |
+          sleep 10  # Даем время для запуска сервера
+          response=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8080)
+          if [ "$response" -eq 200 ]; then
+            echo "Application responded with 200 OK"
+          else
+            echo "Application failed to respond with 200 OK"
+            exit 1
+          fi
+
 
 
